import type { Character } from "@/types/character";

const PRESET_TIMESTAMP = "2026-07-30T00:00:00.000Z";

export const PRESET_CHARACTERS: readonly Character[] = [
  {
    id: "preset-tank-guardian",
    name: "护卫",
    originalPrompt: "坚守阵线的护卫，以厚重盾牌保护自己与同伴。",
    profession: "tank",
    realm: "mortal",
    attack: 9,
    maxHealth: 178,
    skills: [
      { id: "preset-guardian-bulwark", name: "守护壁垒", description: "举起重盾，为自己构筑厚实的防护。", usageText: "举盾守护", type: "shield", activation: "active", target: "self", cooldown: 3, shieldAmount: 45 },
      { id: "preset-guardian-last-stand", name: "不屈坚守", description: "在阵线濒临崩溃时短暂免疫伤害。", usageText: "死守阵线", type: "invincible", activation: "active", target: "self", cooldown: 4 },
    ],
    createdAt: PRESET_TIMESTAMP,
    updatedAt: PRESET_TIMESTAMP,
  },
  {
    id: "preset-tank-swordsman",
    name: "剑客",
    originalPrompt: "身披重甲的剑客，攻守之间始终保持沉着。",
    profession: "tank",
    realm: "mortal",
    attack: 13,
    maxHealth: 152,
    skills: [
      { id: "preset-swordsman-heavy-slash", name: "重甲横斩", description: "以沉重长剑横扫整条敌方阵线。", usageText: "挥剑横扫", type: "cleave_passive", activation: "passive", target: "self", cooldown: 0 },
      { id: "preset-swordsman-armor-break", name: "破甲重斩", description: "借由重甲蓄势，向前排劈出沉重一击。", usageText: "沉肩劈下", type: "damage", activation: "active", target: "enemy_front", cooldown: 3, damageMultiplier: 1.6 },
    ],
    createdAt: PRESET_TIMESTAMP,
    updatedAt: PRESET_TIMESTAMP,
  },
  {
    id: "preset-warrior-vampire",
    name: "吸血鬼",
    originalPrompt: "在月光下作战的吸血鬼，会从战斗间隙恢复精力。",
    profession: "warrior",
    realm: "mortal",
    attack: 20,
    maxHealth: 140,
    skills: [
      { id: "preset-vampire-blood-moon", name: "血月处决", description: "撕咬目标要害，造成暴击并将伤害转化为生命。", usageText: "露出獠牙", type: "critical", activation: "active", target: "enemy_front", cooldown: 4, damageMultiplier: 2 },
      { id: "preset-vampire-drain", name: "鲜血汲取", description: "每次造成伤害后从鲜血中恢复生命。", usageText: "汲取鲜血", type: "lifesteal_passive", activation: "passive", target: "self", cooldown: 0, damageMultiplier: 0.5 },
    ],
    createdAt: PRESET_TIMESTAMP,
    updatedAt: PRESET_TIMESTAMP,
  },
  {
    id: "preset-warrior-spearman",
    name: "长矛手",
    originalPrompt: "训练有素的长矛手，擅长用距离与时机控制战场。",
    profession: "warrior",
    realm: "mortal",
    attack: 19,
    maxHealth: 136,
    skills: [
      { id: "preset-spearman-pierce", name: "贯穿突刺", description: "以长矛精准刺向敌方前排。", usageText: "挺矛突刺", type: "damage", activation: "active", target: "enemy_front", cooldown: 2, damageMultiplier: 1.5 },
      { id: "preset-spearman-formation-break", name: "钩镰破阵", description: "以矛钩打乱敌方前排的行动节奏。", usageText: "横矛牵制", type: "control", activation: "active", target: "enemy_front", cooldown: 4, stunChance: 1 },
    ],
    createdAt: PRESET_TIMESTAMP,
    updatedAt: PRESET_TIMESTAMP,
  },
  {
    id: "preset-mage-warlock",
    name: "术士",
    originalPrompt: "掌握奥术与诅咒的术士，能以冰霜束缚敌人。",
    profession: "mage",
    attack: 20,
    maxHealth: 112,
    realm: "mortal",
    skills: [
      { id: "preset-warlock-arcane-storm", name: "奥术风暴", description: "引爆咒文，打击敌方所有存活角色。", usageText: "引爆咒文", type: "area_damage", activation: "active", target: "enemies_all", cooldown: 3, damageMultiplier: 0.75 },
      { id: "preset-warlock-frost-bind", name: "冰霜禁锢", description: "以寒霜同时冻结敌方全体。", usageText: "降下严寒", type: "area_control", activation: "active", target: "enemies_all", cooldown: 5, stunChance: 1 },
    ],
    createdAt: PRESET_TIMESTAMP,
    updatedAt: PRESET_TIMESTAMP,
  },
  {
    id: "preset-mage-healer",
    name: "治疗师",
    originalPrompt: "专注治疗魔法的治疗师，也会以光束进行自保。",
    profession: "mage",
    attack: 15,
    maxHealth: 122,
    realm: "mortal",
    skills: [
      { id: "preset-healer-restoration", name: "圣愈术", description: "集中圣光恢复己方前排的大量生命。", usageText: "祈唤圣光", type: "heal", activation: "active", target: "ally_front", cooldown: 3, healAmount: 42 },
      { id: "preset-healer-radiance", name: "复苏之环", description: "让治疗光环笼罩所有存活的友军。", usageText: "展开光环", type: "area_heal", activation: "active", target: "allies_all", cooldown: 4, healAmount: 20 },
    ],
    createdAt: PRESET_TIMESTAMP,
    updatedAt: PRESET_TIMESTAMP,
  },
  {
    id: "preset-assassin-samurai",
    name: "武士",
    originalPrompt: "追求一击制胜的武士，凭精准拔刀压迫敌人。",
    profession: "assassin",
    attack: 24,
    maxHealth: 118,
    realm: "mortal",
    skills: [
      { id: "preset-samurai-decisive-cut", name: "一闪绝命", description: "以精准斩击命中敌方前排要害。", usageText: "踏步一闪", type: "critical", activation: "active", target: "enemy_front", cooldown: 4, damageMultiplier: 2 },
      { id: "preset-samurai-duelist", name: "决斗本能", description: "以牺牲部分正面力量为代价，锁定敌方最后的存活角色。", usageText: "锁定要害", type: "assassin_passive", activation: "passive", target: "self", cooldown: 0 },
    ],
    createdAt: PRESET_TIMESTAMP,
    updatedAt: PRESET_TIMESTAMP,
  },
  {
    id: "preset-assassin-winged-beast",
    name: "有翼兽",
    originalPrompt: "自高空俯冲的有翼兽，以速度和爪击解决战斗。",
    profession: "assassin",
    attack: 23,
    maxHealth: 112,
    realm: "mortal",
    skills: [
      { id: "preset-winged-beast-dive", name: "裂空俯冲", description: "自高空俯冲，撕裂敌方后排目标。", usageText: "振翅俯冲", type: "damage", activation: "active", target: "enemy_front", cooldown: 2, damageMultiplier: 1.7 },
      { id: "preset-winged-beast-hunt", name: "猎杀本能", description: "放弃部分正面力量，优先扑向敌方最后的存活角色。", usageText: "锁定猎物", type: "assassin_passive", activation: "passive", target: "self", cooldown: 0 },
    ],
    createdAt: PRESET_TIMESTAMP,
    updatedAt: PRESET_TIMESTAMP,
  },
  {
    id: "preset-ranger-witch",
    name: "女巫",
    originalPrompt: "携带咒术与魔药的女巫，擅长从远处限制敌人。",
    profession: "ranger",
    attack: 26,
    maxHealth: 106,
    realm: "mortal",
    skills: [
      { id: "preset-witch-hex-bolt", name: "腐蚀咒矢", description: "射出附着诅咒的咒能箭矢。", usageText: "低声咏唱", type: "damage", activation: "active", target: "enemy_front", cooldown: 2, damageMultiplier: 1.5 },
      { id: "preset-witch-phoenix-potion", name: "回魂药剂", description: "在首次倒下时饮下秘药，以半数生命重返战场。", usageText: "饮下秘药", type: "revive_passive", activation: "passive", target: "self", cooldown: 0 },
    ],
    createdAt: PRESET_TIMESTAMP,
    updatedAt: PRESET_TIMESTAMP,
  },
  {
    id: "preset-ranger-princess",
    name: "公主",
    originalPrompt: "带领远征队的公主，既会远程作战也懂得照顾自己。",
    profession: "ranger",
    attack: 22,
    maxHealth: 116,
    realm: "mortal",
    skills: [
      { id: "preset-princess-royal-arrow", name: "王室连矢", description: "以训练有素的射术持续压制敌方前排。", usageText: "搭弓连射", type: "damage", activation: "active", target: "enemy_front", cooldown: 2, damageMultiplier: 1.3 },
      { id: "preset-princess-rally", name: "远征号令", description: "每次行动后气势更盛，攻击会持续成长。", usageText: "发出号令", type: "growth_passive", activation: "passive", target: "self", cooldown: 0, damageMultiplier: 0.2 },
    ],
    createdAt: PRESET_TIMESTAMP,
    updatedAt: PRESET_TIMESTAMP,
  },
];

export function getPresetCharacters(): Character[] {
  return PRESET_CHARACTERS.map((character) => ({
    ...character,
    skills: character.skills.map((skill) => ({ ...skill })) as Character["skills"],
  }));
}
